/* =========================================================
   RETROVAULT — product catalog
   category: "console" | "game" | "accessoire"
   platform: "PSP" | "PS1" | "GBA" | "N64" | "Universeel"
   stock: aantal op voorraad (0 = uitverkocht)
   ========================================================= */

const PRODUCTS = [
  // ---------------- CONSOLES ----------------
  {
    id: "c-psp-1000",
    name: "PSP 1000 \"Phat\" — Gereviseerd",
    category: "console",
    platform: "PSP",
    price: 89.00,
    oldPrice: 109.00,
    stock: 6,
    glyph: "🎮",
    tag: "Bestseller",
    short: "De originele PSP, volledig gereviseerd met nieuwe accu en gepolijste behuizing.",
    description: "De PSP 1000 was Sony's eerste handheld-aanval op de gamingmarkt, en deze staat er nog steeds. Elk exemplaar is grondig getest, voorzien van een nieuwe accu en gereinigd UMD-lezerskopje. Inclusief oplader.",
    specs: {
      "Scherm": "4.3\" LCD, 480×272",
      "Opslag": "Memory Stick Pro Duo (los verkrijgbaar)",
      "Accu": "Nieuw, ±4-6 uur speeltijd",
      "Conditie": "Gereviseerd, lichte gebruikssporen mogelijk",
      "Inbegrepen": "Console, oplader, 30 dagen garantie"
    }
  },
  {
    id: "c-psp-2000",
    name: "PSP 2000 \"Slim & Lite\" — Zwart",
    category: "console",
    platform: "PSP",
    price: 99.00,
    stock: 4,
    glyph: "🎮",
    tag: "Populair",
    short: "Dunner, lichter en met TV-out. De meest gebalanceerde PSP-revisie.",
    description: "De PSP 2000 verbetert alles aan de originele: een dunnere behuizing, sneller opstarten en video-uitgang voor op de tv. Deze unit is compleet gereviseerd en klaar voor je gameverzameling.",
    specs: {
      "Scherm": "4.3\" LCD, 480×272",
      "Opslag": "Memory Stick Pro Duo (los verkrijgbaar)",
      "Extra": "TV-out via componentkabel",
      "Conditie": "Gereviseerd, A-grade behuizing",
      "Inbegrepen": "Console, oplader, 30 dagen garantie"
    }
  },
  {
    id: "c-psp-3000",
    name: "PSP 3000 — Wit",
    category: "console",
    platform: "PSP",
    price: 109.00,
    stock: 2,
    glyph: "🎮",
    tag: "Laatste stuks",
    short: "Verbeterd scherm met minder ghosting en ingebouwde microfoon.",
    description: "De PSP 3000 heeft een merkbaar beter LCD-scherm met snellere responstijd en anti-ghosting technologie, plus een ingebouwde microfoon. De topversie van de klassieke PSP-lijn.",
    specs: {
      "Scherm": "4.3\" LCD, verbeterd contrast",
      "Opslag": "Memory Stick Pro Duo (los verkrijgbaar)",
      "Extra": "Ingebouwde microfoon",
      "Conditie": "Gereviseerd, uitstekende staat",
      "Inbegrepen": "Console, oplader, 30 dagen garantie"
    }
  },
  {
    id: "c-psp-go",
    name: "PSP Go — Digitale Editie",
    category: "console",
    platform: "PSP",
    price: 129.00,
    stock: 0,
    glyph: "🎮",
    tag: "Uitverkocht",
    short: "Compacte schuifmodel zonder UMD-drive, gericht op digitale games.",
    description: "De zeldzame PSP Go met schuifscherm en 16GB interne opslag. Geen UMD-drive — puur digitaal. Een gewild verzamelobject.",
    specs: {
      "Scherm": "3.8\" LCD, 480×272",
      "Opslag": "16GB intern + Memory Stick Micro",
      "Vorm": "Schuifmodel, geen UMD-drive",
      "Conditie": "Gereviseerd",
      "Inbegrepen": "Console, oplader, 30 dagen garantie"
    }
  },
  {
    id: "c-ps1-classic",
    name: "PlayStation 1 (SCPH-9000) — Gereviseerd",
    category: "console",
    platform: "PS1",
    price: 79.00,
    stock: 5,
    glyph: "📀",
    tag: "Klassieker",
    short: "De laatste PS1-revisie, compact en betrouwbaar, met nieuwe laserlens.",
    description: "Deze late-model PS1 heeft een vervangen laserlens voor betrouwbaar lezen van je schijven en is volledig getest op alle poorten en de voedingseenheid.",
    specs: {
      "Model": "SCPH-9000 (laatste revisie)",
      "Video": "Composiet / RGB Scart mogelijk",
      "Conditie": "Gereviseerd, nieuwe laser",
      "Inbegrepen": "Console, voeding, AV-kabel, 1 controller"
    }
  },
  {
    id: "c-gba-sp",
    name: "Game Boy Advance SP — Gereviseerd",
    category: "console",
    platform: "GBA",
    price: 69.00,
    stock: 8,
    glyph: "🕹️",
    tag: null,
    short: "Klapmodel met ingebouwde verlichting en oplaadbare accu.",
    description: "De GBA SP blijft een publiekslieveling: klein, met frontlicht en een oplaadbare accu in plaats van AA-batterijen. Perfect voor onderweg gamen.",
    specs: {
      "Scherm": "2.9\" TFT met frontlight",
      "Accu": "Oplaadbaar, ingebouwd",
      "Conditie": "Gereviseerd",
      "Inbegrepen": "Console, oplader, 30 dagen garantie"
    }
  },
  {
    id: "c-n64",
    name: "Nintendo 64 — Gereviseerd",
    category: "console",
    platform: "N64",
    price: 99.00,
    stock: 3,
    glyph: "🕹️",
    tag: null,
    short: "De iconische 3D-pionier, compleet getest en gereinigd.",
    description: "Deze N64 is volledig gereinigd, getest op alle cartridge-contacten en voorzien van een nieuwe AV-kabel. Klaar om je klassiekers weer op te starten.",
    specs: {
      "Video": "Composiet AV",
      "Conditie": "Gereviseerd, gereinigde cartridgepoort",
      "Inbegrepen": "Console, voeding, AV-kabel, 1 controller"
    }
  },

  // ---------------- PSP GAMES ----------------
  {
    id: "g-psp-gow-cos",
    name: "God of War: Chains of Olympus",
    category: "game",
    platform: "PSP",
    price: 24.00,
    stock: 7,
    glyph: "💿",
    tag: "Topgame",
    short: "Actie-avontuur waarin Kratos strijdt tegen de goden van de onderwereld.",
    description: "Een van de best beoordeelde PSP-titels ooit. Chains of Olympus brengt de intense actie van de hoofdreeks naar de handheld, met verrassend goede graphics voor zijn tijd.",
    specs: { "Formaat": "UMD", "Genre": "Actie-avontuur", "Conditie": "Compleet in doosje, incl. hoesje" }
  },
  {
    id: "g-psp-lumines",
    name: "Lumines",
    category: "game",
    platform: "PSP",
    price: 14.00,
    stock: 9,
    glyph: "💿",
    tag: null,
    short: "Verslavende puzzelgame met muziek die meebeweegt met je acties.",
    description: "Een hypnotiserende blokkenpuzzel waarbij de muziek dynamisch reageert op je spel. Een van de betere launch-titels van de PSP.",
    specs: { "Formaat": "UMD", "Genre": "Puzzel", "Conditie": "Compleet in doosje" }
  },
  {
    id: "g-psp-mgs-pw",
    name: "Metal Gear Solid: Peace Walker",
    category: "game",
    platform: "PSP",
    price: 29.00,
    stock: 4,
    glyph: "💿",
    tag: "Zeldzaam",
    short: "Volwaardige MGS-titel exclusief voor PSP, met co-op modus.",
    description: "Een van de meest ambitieuze PSP-games ooit gemaakt — een volwaardig Metal Gear-avontuur met basisbouw, co-op missies en een epische verhaallijn.",
    specs: { "Formaat": "UMD", "Genre": "Actie / Stealth", "Conditie": "Compleet in doosje, incl. boekje" }
  },
  {
    id: "g-psp-patapon",
    name: "Patapon",
    category: "game",
    platform: "PSP",
    price: 19.00,
    stock: 6,
    glyph: "💿",
    tag: null,
    short: "Ritmegame waarin je een legertje trommelt naar de overwinning.",
    description: "Een unieke mix van ritmegame en strategie, met een herkenbare handgetekende stijl. Trommel je Patapon-leger naar de overwinning.",
    specs: { "Formaat": "UMD", "Genre": "Ritme / Strategie", "Conditie": "Compleet in doosje" }
  },
  {
    id: "g-psp-ff-crisis",
    name: "Crisis Core: Final Fantasy VII",
    category: "game",
    platform: "PSP",
    price: 34.00,
    stock: 3,
    glyph: "💿",
    tag: "Fan-favoriet",
    short: "Prequel op FFVII die het verhaal van Zack Fair vertelt.",
    description: "Een emotioneel actie-RPG dat het lot van Zack Fair volgt, jaren voor de gebeurtenissen van Final Fantasy VII. Een absolute must voor RPG-fans.",
    specs: { "Formaat": "UMD", "Genre": "Actie-RPG", "Conditie": "Compleet in doosje, incl. boekje" }
  },
  {
    id: "g-psp-daxter",
    name: "Daxter",
    category: "game",
    platform: "PSP",
    price: 17.00,
    stock: 5,
    glyph: "💿",
    tag: null,
    short: "Platformer spin-off met de sidekick uit Jak & Daxter in de hoofdrol.",
    description: "Daxter neemt het heft in eigen handen in deze platformer vol humor, strakke besturing en verrassend gepolijste graphics voor de PSP.",
    specs: { "Formaat": "UMD", "Genre": "Platformer", "Conditie": "Compleet in doosje" }
  },
  {
    id: "g-psp-tekken6",
    name: "Tekken 6",
    category: "game",
    platform: "PSP",
    price: 21.00,
    stock: 0,
    glyph: "💿",
    tag: "Uitverkocht",
    short: "Volledige vechtgame-roster onderweg meenemen.",
    description: "Een indrukwekkend complete vechtgame-poort met bijna de volledige console-roster, inclusief Scenario Campaign modus.",
    specs: { "Formaat": "UMD", "Genre": "Vechtgame", "Conditie": "Compleet in doosje" }
  },
  {
    id: "g-psp-wipeout",
    name: "WipEout Pure",
    category: "game",
    platform: "PSP",
    price: 16.00,
    stock: 6,
    glyph: "💿",
    tag: null,
    short: "Futuristische anti-zwaartekracht racer met pompende soundtrack.",
    description: "Bloedsnelle anti-zwaartekracht races met een iconische elektronische soundtrack. Een schoolvoorbeeld van wat de PSP grafisch kon.",
    specs: { "Formaat": "UMD", "Genre": "Racing", "Conditie": "Compleet in doosje" }
  },

  // ---------------- ACCESSOIRES ----------------
  {
    id: "a-psp-case",
    name: "PSP Beschermhoes — Universeel",
    category: "accessoire",
    platform: "PSP",
    price: 12.00,
    stock: 20,
    glyph: "🧳",
    tag: null,
    short: "Stevige hoes met vakjes voor UMD's, past op alle PSP-modellen.",
    description: "Gevoerde beschermhoes met ritssluiting, ruimte voor de console plus vier UMD-schijfjes. Past op PSP 1000, 2000 en 3000.",
    specs: { "Materiaal": "Nylon, gevoerd", "Past op": "PSP 1000 / 2000 / 3000", "Kleur": "Zwart" }
  },
  {
    id: "a-psp-charger",
    name: "PSP Oplader (vervanging)",
    category: "accessoire",
    platform: "PSP",
    price: 9.00,
    stock: 15,
    glyph: "🔌",
    tag: null,
    short: "Originele-specificatie oplader voor alle PSP-modellen.",
    description: "Een betrouwbare vervangingsoplader met dezelfde specificaties als de originele Sony-adapter. Geschikt voor PSP 1000, 2000, 3000 en Go.",
    specs: { "Uitgang": "5V, 2A", "Past op": "PSP 1000 / 2000 / 3000 / Go" }
  },
  {
    id: "a-psp-memstick",
    name: "Memory Stick Pro Duo 4GB",
    category: "accessoire",
    platform: "PSP",
    price: 15.00,
    stock: 10,
    glyph: "💾",
    tag: null,
    short: "Geheugenkaart voor savegames, homebrew en muziek.",
    description: "Betrouwbare 4GB Memory Stick Pro Duo, compatibel met alle PSP-modellen. Ideaal voor savegames, foto's en muziek.",
    specs: { "Capaciteit": "4GB", "Type": "Memory Stick Pro Duo" }
  },
  {
    id: "a-psp-screen",
    name: "PSP Screenprotector (2-pack)",
    category: "accessoire",
    platform: "PSP",
    price: 6.00,
    stock: 25,
    glyph: "🧼",
    tag: null,
    short: "Krasbestendige folie op maat gesneden voor het PSP-scherm.",
    description: "Set van twee screenprotectors, precisiegesneden voor het 4.3\" PSP-scherm. Inclusief microvezeldoekje en applicatiekaart.",
    specs: { "Inhoud": "2 protectors + doekje", "Past op": "PSP 1000 / 2000 / 3000" }
  },
  {
    id: "a-ps1-controller",
    name: "PS1 Controller (Dual Analog)",
    category: "accessoire",
    platform: "PS1",
    price: 18.00,
    stock: 9,
    glyph: "🎮",
    tag: null,
    short: "Gereviseerde originele controller met werkende analoge sticks.",
    description: "Getest en gereinigd, met soepel werkende analoge sticks en knoppen. Geschikt voor alle PS1- en PS2-consoles.",
    specs: { "Type": "Dual Analog (SCPH-1200)", "Conditie": "Gereviseerd en getest" }
  },
  {
    id: "a-n64-controller",
    name: "N64 Controller — Grijs",
    category: "accessoire",
    platform: "N64",
    price: 22.00,
    stock: 7,
    glyph: "🕹️",
    tag: null,
    short: "Originele controller met nieuwe joystick-mechaniek.",
    description: "Deze N64-controller is voorzien van een vervangen joystick-mechaniek tegen het beruchte 'los spelen' van de stick.",
    specs: { "Kleur": "Grijs", "Conditie": "Gereviseerd, nieuwe joystick" }
  },
  {
    id: "a-gba-link",
    name: "GBA Link Kabel",
    category: "accessoire",
    platform: "GBA",
    price: 8.00,
    stock: 12,
    glyph: "🔗",
    tag: null,
    short: "Voor multiplayer sessies tussen twee Game Boy Advance consoles.",
    description: "Verbind twee GBA's (of SP's) voor multiplayer games en trades. Een essentieel accessoire voor Pokémon-ruilen.",
    specs: { "Lengte": "1.2m", "Compatibel": "GBA / GBA SP" }
  },
  {
    id: "a-universal-cleaning",
    name: "Retro Cleaning Kit",
    category: "accessoire",
    platform: "Universeel",
    price: 13.00,
    stock: 18,
    glyph: "🧽",
    tag: null,
    short: "Reinig cartridge-contacten en UMD-lenzen veilig en effectief.",
    description: "Complete set met reinigingsvloeistof, wattenstaafjes en een microvezeldoekje om je retro cartridges, schijfjes en consolepoorten schoon te houden.",
    specs: { "Inhoud": "Vloeistof, staafjes, doekje", "Geschikt voor": "Cartridges, UMD, poorten" }
  },

  // ---------------- ABEL123 DIGITALE PRODUCTEN & GAMES ----------------
  {
    id: "p-psp-portable",
    name: "Brand New! Abel123 PSP Gaming Portable (10,000+ Games)",
    category: "console",
    platform: "PSP",
    price: 149.99,
    stock: 10,
    glyph: "🎮",
    tag: "Nieuw",
    short: "Draagbare PSP-gamingconsole met meer dan 10.000 voorgeladen games.",
    description: "Een gloednieuwe draagbare gamingconsole in PSP-stijl, kant-en-klaar geladen met meer dan 10.000 games.",
    specs: { "Type": "Handheld console", "Inhoud": "10.000+ voorgeladen games" },
    paypalId: "BNTR9J25Q3DW2",
    weroUrl: "https://buy.stripe.com/eVq4gs4ty8sRh19eND6Zy00"
  },
  {
    id: "p-gameboy-retro",
    name: "Brand New! Abel123 Game Boy Retro Console (400+ Games) 2Players",
    category: "console",
    platform: "Universeel",
    price: 49.99,
    stock: 10,
    glyph: "🎮",
    tag: "Nieuw",
    short: "Retro Game Boy-stijl console voor 2 spelers met 400+ games.",
    description: "Een nieuwe retro-console geïnspireerd op de Game Boy, met meer dan 400 ingebouwde games en 2-speler ondersteuning.",
    specs: { "Type": "Handheld console", "Spelers": "2", "Inhoud": "400+ voorgeladen games" },
    paypalId: "HA9MA4EPEGKF8",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-emulator",
    name: "Abel123 Emulator",
    category: "accessoire",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💾",
    tag: null,
    short: "Software-emulator voor het spelen van klassieke retro-games.",
    description: "Een digitale emulator waarmee je klassieke retro-games kunt spelen op je eigen apparaat.",
    specs: { "Type": "Digitale download" },
    paypalId: "JE3WG2B8ADT28"
  },
  {
    id: "p-ai-music-studio",
    name: "Abelsoftware123 AI Music Studio",
    category: "accessoire",
    platform: "Universeel",
    price: 14.99,
    stock: 999,
    glyph: "🎵",
    tag: "Populair",
    short: "AI-gestuurde muziekstudio-software.",
    description: "Software waarmee je met behulp van AI muziek kunt maken en produceren.",
    specs: { "Type": "Digitale download" },
    paypalId: "EF7N5A3CMKHEL",
    weroUrl: "https://buy.stripe.com/dRmcMYgcgdNb9yH34V6Zy05"
  },
  {
    id: "p-game-launcher",
    name: "Abel123 Game Launcher",
    category: "accessoire",
    platform: "Universeel",
    price: 9.99,
    stock: 999,
    glyph: "🕹️",
    tag: null,
    short: "Launcher-software om je gamecollectie te beheren en starten.",
    description: "Een overzichtelijke launcher waarmee je al je games op één plek kunt beheren en starten.",
    specs: { "Type": "Digitale download" },
    paypalId: "HF6PVP6DVYE7Q",
    weroUrl: "https://buy.stripe.com/5kQdR28JOeRfeT1bBr6Zy03"
  },
  {
    id: "p-apps-maker",
    name: "Abel123 Apps Maker",
    category: "accessoire",
    platform: "Universeel",
    price: 49.99,
    stock: 999,
    glyph: "🛠️",
    tag: null,
    short: "Tool waarmee je zelf apps kunt bouwen zonder programmeerkennis.",
    description: "Een softwarepakket waarmee gebruikers eenvoudig eigen apps kunnen samenstellen.",
    specs: { "Type": "Digitale download" },
    paypalId: "LN7JZRSCZ2EL8",
    weroUrl: "https://buy.stripe.com/aFabIU2lq24t9yH5d36Zy04"
  },
  {
    id: "p-mp3-converter",
    name: "Abel123 MP3 Converter",
    category: "accessoire",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "🎧",
    tag: null,
    short: "Converteer audio- en videobestanden eenvoudig naar MP3.",
    description: "Handige converter-software voor het omzetten van bestanden naar MP3-formaat.",
    specs: { "Type": "Digitale download" },
    paypalId: "8Q7HGA3LPLYP2"
  },
  {
    id: "p-super-world-6",
    name: "Super Abel123 World 6",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 6 in de Super Abel123 World-reeks.",
    description: "Het zesde deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "M9MX6EK55RXKQ"
  },
  {
    id: "p-super-world-5",
    name: "Super Abel123 World 5",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 5 in de Super Abel123 World-reeks.",
    description: "Het vijfde deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "KZARPPBDHK7AW"
  },
  {
    id: "p-super-world-4",
    name: "Super Abel123 World 4",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 4 in de Super Abel123 World-reeks.",
    description: "Het vierde deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "L58Z9WU6GQSCY"
  },
  {
    id: "p-super-world-3",
    name: "Super Abel123 World 3",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 3 in de Super Abel123 World-reeks.",
    description: "Het derde deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "B8DRLNMMXSHXC"
  },
  {
    id: "p-super-world-2",
    name: "Super Abel123 World 2",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 2 in de Super Abel123 World-reeks.",
    description: "Het tweede deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "F33GLB3W3CP7N"
  },
  {
    id: "p-super-world-1",
    name: "Super Abel123 World 1",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 1 in de Super Abel123 World-reeks.",
    description: "Het eerste deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "7DWU56DLEMYLU"
  },
  {
    id: "p-wmwario-android",
    name: "WMWario 90s · 2030 · Builder · Matrix · Dimension (Android)",
    category: "game",
    platform: "Universeel",
    price: 9.99,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Bundel Android-games in de WMWario-reeks.",
    description: "Een bundel van meerdere WMWario Android-games in verschillende thema's.",
    specs: { "Platform": "Android", "Formaat": "Digitale download" },
    paypalId: "P3TZE99UGD9EY",
    weroUrl: "https://buy.stripe.com/5kQdR28JOeRfeT1bBr6Zy03"
  },
  {
    id: "p-demolition-game",
    name: "Abel123 Demolition Game",
    category: "game",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Actiegame rondom sloop- en vernietigingsuitdagingen.",
    description: "Een actiegame waarin je gebouwen en objecten mag slopen.",
    specs: { "Genre": "Actie", "Formaat": "Digitale download" },
    paypalId: "HMTVUK97GVGNG",
    weroUrl: "https://buy.stripe.com/14A9AM2lq6kJ26f34V6Zy08"
  },
  {
    id: "p-mars-climb",
    name: "Mars Climb Spacer",
    category: "game",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "🚀",
    tag: null,
    short: "Klimgame in een Mars-thema.",
    description: "Een casual klim/platformgame met een ruimtethema op Mars.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "RYXEHD683PCWY",
    weroUrl: "https://buy.stripe.com/14A9AM2lq6kJ26f34V6Zy08"
  },
  {
    id: "p-moon-climb",
    name: "Moon Climb Spacer",
    category: "game",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "🚀",
    tag: null,
    short: "Klimgame in een maanthema.",
    description: "Een casual klim/platformgame met een ruimtethema op de maan.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "ASP4MBWQKHYS4",
    weroUrl: "https://buy.stripe.com/14A9AM2lq6kJ26f34V6Zy08"
  },

  // ---------------- WMWARIO REEKS ----------------
  {
    id: "p-wmwario-luigi-3d",
    name: "WMWario & Luigi 3D Happy World (Multiplayer)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "3D multiplayer platformgame in de WMWario-reeks.",
    description: "Een 3D platformgame met multiplayer-ondersteuning uit de WMWario Happy World-serie.",
    specs: { "Genre": "3D Platformer", "Multiplayer": "Ja", "Formaat": "Digitale download" },
    paypalId: "U5GBLF47SEUC6",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-wmwario-2026",
    name: "WMWario Happy World 2026 (8-in-1 PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "8-in-1 pc-gamebundel in de WMWario Happy World-reeks.",
    description: "Een bundel van acht games in één pc-pakket uit de WMWario Happy World-serie.",
    specs: { "Platform": "PC", "Inhoud": "8-in-1 bundel", "Formaat": "Digitale download" },
    paypalId: "MNRG8ZTCQE9LJ",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-wmwario-fantasy",
    name: "WMWario Happy World Fantasy (Webserver)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Webserver-versie van WMWario Happy World in een fantasy-thema.",
    description: "Een via webserver speelbare versie van WMWario Happy World met een fantasy-thema.",
    specs: { "Platform": "Webserver", "Formaat": "Digitale download" },
    paypalId: "USH33D3ECTQBN",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-wmwario-12",
    name: "WMWario Happy World 12 (PC)",
    category: "game",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 12 van de WMWario Happy World pc-reeks.",
    description: "Het twaalfde deel in de WMWario Happy World pc-gameserie.",
    specs: { "Platform": "PC", "Formaat": "Digitale download" },
    paypalId: "9DYATEXHR22U4",
    weroUrl: "https://buy.stripe.com/14A9AM2lq6kJ26f34V6Zy08"
  },
  {
    id: "p-wmwario-11",
    name: "WMWario Happy World 11 (PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 11 van de WMWario Happy World pc-reeks.",
    description: "Het elfde deel in de WMWario Happy World pc-gameserie.",
    specs: { "Platform": "PC", "Formaat": "Digitale download" },
    paypalId: "WXQZ6GHP3S8KG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-wmwario-10",
    name: "WMWario Happy World 10 (PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 10 van de WMWario Happy World pc-reeks.",
    description: "Het tiende deel in de WMWario Happy World pc-gameserie.",
    specs: { "Platform": "PC", "Formaat": "Digitale download" },
    paypalId: "NEDQ4N36E8HCG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-wmwario-9",
    name: "WMWario Happy World 9 (PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 9 van de WMWario Happy World pc-reeks.",
    description: "Het negende deel in de WMWario Happy World pc-gameserie.",
    specs: { "Platform": "PC", "Formaat": "Digitale download" },
    paypalId: "LXTBSKQCJW3AY",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-wmwario-8",
    name: "WMWario Happy World 8 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 8 van de WMWario Happy World-reeks, voor Android en pc.",
    description: "Het achtste deel in de WMWario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "U5CKDXUJ66V74",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-wmwario-6",
    name: "WMWario Happy World 6 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 6 van de WMWario Happy World-reeks, voor Android en pc.",
    description: "Het zesde deel in de WMWario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "UZJJKSP9FLMQ8",
    weroUrl: "https://buy.stripe.com/14A9AM2lq6kJ26f34V6Zy08"
  },
  {
    id: "p-wmwario-4",
    name: "WMWario Happy World 4 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 4 van de WMWario Happy World-reeks, voor Android en pc.",
    description: "Het vierde deel in de WMWario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "LKDVU4S7693HA",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },
  {
    id: "p-wmwario-3",
    name: "WMWario Happy World 3 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 9.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 3 van de WMWario Happy World-reeks, voor Android en pc.",
    description: "Het derde deel in de WMWario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "E5NAUQHKLVA86",
    weroUrl: "https://buy.stripe.com/5kQdR28JOeRfeT1bBr6Zy03"
  },
  {
    id: "p-wmwario-2",
    name: "WMWario Happy World 2 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 2 van de WMWario Happy World-reeks, voor Android en pc.",
    description: "Het tweede deel in de WMWario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "YHY5GEYZB6NB8",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-wmwario-1",
    name: "WMWario Happy World 1 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 1 van de WMWario Happy World-reeks, voor Android en pc.",
    description: "Het eerste deel in de WMWario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "KPHFXFJ5SAFKJ",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-wmwario-happy-app",
    name: "WMWario Happy (Android App)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Android-app in de WMWario Happy-reeks.",
    description: "Een Android-app uit de WMWario Happy-serie.",
    specs: { "Platform": "Android", "Formaat": "Digitale download" },
    paypalId: "7L36E2XCNG9B2",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },

  // ---------------- OVERIGE ANDROID GAMES & APPS ----------------
  {
    id: "p-slotpipes",
    name: "WMWario Slotpipes (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Puzzelgame met slots en pijpen, voor Android.",
    description: "Een Android-puzzelgame waarin je pijpen en slots met elkaar verbindt.",
    specs: { "Platform": "Android", "Genre": "Puzzel", "Formaat": "Digitale download" },
    paypalId: "AS8XU2UTZUFDA",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },
  {
    id: "p-fluppy-burd",
    name: "Fluppy Burd Blocks (Android)",
    category: "game",
    platform: "Universeel",
    price: 1.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Casual blokkenpuzzel-vogelgame voor Android.",
    description: "Een luchtige casual game met blokken en een vogel als hoofdpersonage, voor Android.",
    specs: { "Platform": "Android", "Genre": "Puzzel", "Formaat": "Digitale download" },
    paypalId: "CSJAKU42XZLG6",
    weroUrl: "https://buy.stripe.com/eVq14g3pugZn7qz6h76Zy0a"
  },
  {
    id: "p-slotmoji",
    name: "SlotMoji (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Emoji-thema slotgame voor Android.",
    description: "Een casual slotgame met een emoji-thema, voor Android.",
    specs: { "Platform": "Android", "Genre": "Casual", "Formaat": "Digitale download" },
    paypalId: "YT7YX5KJUAC94",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },
  {
    id: "p-wmwario-crush",
    name: "WMWario Crush Saga (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Match-stijl puzzelgame voor Android in de WMWario-reeks.",
    description: "Een match-gebaseerde puzzelgame uit de WMWario-serie, voor Android.",
    specs: { "Platform": "Android", "Genre": "Puzzel", "Formaat": "Digitale download" },
    paypalId: "FJCQPYBAD5UG4",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },
  {
    id: "p-kross-zero",
    name: "Kross and Zero (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Boter-kaas-en-eieren-stijl game voor Android.",
    description: "Een Android-game geïnspireerd op het klassieke Kruisje-Rondje spel.",
    specs: { "Platform": "Android", "Genre": "Puzzel / Bordspel", "Formaat": "Digitale download" },
    paypalId: "7K2GYD5LUSSJ4",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },
  {
    id: "p-yf-arrows",
    name: "YF Arrows (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.00,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Pijl-gebaseerde puzzelgame voor Android.",
    description: "Een Android-puzzelgame gebaseerd op het richten en verbinden van pijlen.",
    specs: { "Platform": "Android", "Genre": "Puzzel", "Formaat": "Digitale download" },
    paypalId: "6GVUTFNE3KLDU",
    weroUrl: "https://buy.stripe.com/9B6eV62lqgZn3aj6h76Zy09"
  },
  {
    id: "p-flying-dutchman",
    name: "Flying Dutchman (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Avonturengame in nautisch thema voor Android.",
    description: "Een Android-avonturengame geïnspireerd op de legende van de Vliegende Hollander.",
    specs: { "Platform": "Android", "Genre": "Avontuur", "Formaat": "Digitale download" },
    paypalId: "YJUU798QTPPHY",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  }
];

/* Helper lookups */
function getProductById(id){
  return PRODUCTS.find(p => p.id === id);
}
function formatPrice(n){
  return "€ " + n.toFixed(2).replace(".", ",");
}
