/* =========================================================
   RETROVAULT — product catalog
   category: "console" | "game" | "accessoire"
   platform: "PSP" | "PS1" | "GBA" | "N64" | "Universeel"
   stock: aantal op voorraad (0 = uitverkocht)
   ========================================================= */

const PRODUCTS = [
  // ---------------- ABEL123 DIGITALE PRODUCTEN & GAMES ----------------
  {
    id: "p-psp-portable",
    name: "Brand New! Abel123 PSP Gaming Portable (10,000+ Games) Kleur: Zwart,Wit",
    category: "console",
    platform: "PSP",
    price: 149.99,
    stock: 10,
    glyph: "🎮",
    tag: "Nieuw",
    short: "Draagbare PSP-gamingconsole met meer dan 10.000 voorgeladen games.",
    description: "Een gloednieuwe draagbare gamingconsole in PSP-stijl, kant-en-klaar geladen met meer dan 10.000 games.",
    specs: { "Type": "Handheld console", "Inhoud": "10.000+ voorgeladen games" },
    paypalId: "BNTR9J25Q3DW2",
    image: "https://pics.paypal.com/00/p/ODcyYWFjYTYtOTAxMy00MjVlLThiNDYtMjkxYjc2ZjViMWIx/image_2.JPG",
    weroUrl: "https://buy.stripe.com/eVq4gs4ty8sRh19eND6Zy00"
  },
  {
    id: "p-gameboy-retro",
    name: "Brand New! Abel123 Game Boy Retro Console (400+ Games) 2Spelers Kleur: Blauw,Rood,Geel,Zwart",
    category: "console",
    platform: "Universeel",
    price: 49.99,
    stock: 10,
    glyph: "🎮",
    tag: "Nieuw",
    short: "Retro Game Boy-stijl console voor 2 spelers met 400+ games.",
    description: "Een nieuwe retro-console geïnspireerd op de Game Boy, met meer dan 400 ingebouwde games en 2-speler ondersteuning.",
    specs: { "Type": "Handheld console", "Spelers": "2", "Inhoud": "400+ voorgeladen games" },
    paypalId: "HA9MA4EPEGKF8",
    image: "https://pics.paypal.com/00/p/M2E1NGY1ZmUtYTdkMC00M2E3LWEzNTctNWI2YjgyNDI5Yjhk/image_2.JPG",
    weroUrl: "https://buy.stripe.com/aFabIU2lq24t9yH5d36Zy04"
  },
  {
    id: "p-emulator",
    name: "Abel123 Emulator",
    category: "accessoire",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💾",
    tag: null,
    short: "Software-emulator voor het spelen van klassieke retro-games.",
    description: "Een digitale emulator waarmee je klassieke retro-games kunt spelen op je eigen apparaat.",
    specs: { "Type": "Digitale download" },
    paypalId: "JE3WG2B8ADT28",
    image: "https://pics.paypal.com/00/p/MTlmZmRjNTAtYjBiMi00NjBiLTg4M2QtYjE3YjBmNjUxNjM0/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-ai-music-studio",
    name: "Abelsoftware123 AI Music Studio",
    category: "accessoire",
    platform: "Universeel",
    price: 14.99,
    stock: 999,
    glyph: "🎵",
    tag: "Populair",
    short: "AI-gestuurde muziekstudio-software.",
    description: "Software waarmee je met behulp van AI muziek kunt maken en produceren.",
    specs: { "Type": "Digitale download" },
    paypalId: "EF7N5A3CMKHEL",
    image: "https://pics.paypal.com/00/p/OTQ0YTQ4ZjktMjA2Ni00ZTU0LWE4MTEtMzBkODMwMTFiNWUz/image_2.JPG",
    weroUrl: "https://buy.stripe.com/dRmcMYgcgdNb9yH34V6Zy05"
  },
  {
    id: "p-game-launcher",
    name: "Abel123 Game Launcher",
    category: "accessoire",
    platform: "Universeel",
    price: 9.99,
    stock: 999,
    glyph: "🕹️",
    tag: null,
    short: "Launcher-software om je gamecollectie te beheren en starten.",
    description: "Een overzichtelijke launcher waarmee je al je games op één plek kunt beheren en starten.",
    specs: { "Type": "Digitale download" },
    paypalId: "HF6PVP6DVYE7Q",
    image: "https://pics.paypal.com/00/p/ZjQ3YjJhYzItZWY4OS00ZGZkLTlmYTEtNTUxYTY2ZWY2NzZk/image_2.JPG",
    weroUrl: "https://buy.stripe.com/5kQdR28JOeRfeT1bBr6Zy03"
  },
  {
    id: "p-apps-maker",
    name: "Abel123 Android Apps Maker",
    category: "accessoire",
    platform: "Universeel",
    price: 39.99,
    stock: 999,
    glyph: "🛠️",
    tag: null,
    short: "Tool waarmee je zelf apps kunt bouwen zonder programmeerkennis.",
    description: "Een softwarepakket waarmee gebruikers eenvoudig eigen apps kunnen samenstellen.",
    specs: { "Type": "Digitale download" },
    paypalId: "LN7JZRSCZ2EL8",
    image: "https://pics.paypal.com/00/p/NjY3YzUzYWMtNzlmNS00ZWNlLWIyNjYtZjNiMWNjMGZjZTM5/image_2.JPG",
    weroUrl: "https://buy.stripe.com/fZu3co7FK38x4en0WN6Zy0b"
  },
  {
    id: "p-mp3-converter",
    name: "Abel123 MP3 Converter",
    category: "accessoire",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "🎧",
    tag: null,
    short: "Converteer audio- en videobestanden eenvoudig naar MP3.",
    description: "Handige converter-software voor het omzetten van bestanden naar MP3-formaat.",
    specs: { "Type": "Digitale download" },
    paypalId: "8Q7HGA3LPLYP2",
    image: "https://pics.paypal.com/00/p/NTkyZWNkZTUtZmYyMC00MzQ1LWEwZTktYTk0Yjg0M2QzM2Jj/image_2.JPG",
    weroUrl: "https://buy.stripe.com/14A9AM2lq6kJ26f34V6Zy08"
  },
  {
    id: "p-super-world-6",
    name: "Super Abel123 World 6",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 6 in de Super Abel123 World-reeks.",
    description: "Het zesde deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "M9MX6EK55RXKQ",
    image: "https://pics.paypal.com/00/p/ZjA5MWY0M2EtYzY2Yi00NDBjLTgwNjQtZGJhNjNlYzA2MTI4/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-super-world-5",
    name: "Super Abel123 World 5",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 5 in de Super Abel123 World-reeks.",
    description: "Het vijfde deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "KZARPPBDHK7AW",
    image: "https://pics.paypal.com/00/p/YzkyMDQzMzQtZDQ4NS00YWY1LWE3NzItZWZmY2IyNDE0MWU0/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-super-world-4",
    name: "Super Abel123 World 4",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 4 in de Super Abel123 World-reeks.",
    description: "Het vierde deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "L58Z9WU6GQSCY",
    image: "https://pics.paypal.com/00/p/OTk3Yjg4MjAtNmFjMC00M2FhLTgzMzQtOGM5NzA4ODljN2Uz/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-super-world-3",
    name: "Super Abel123 World 3",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 3 in de Super Abel123 World-reeks.",
    description: "Het derde deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "B8DRLNMMXSHXC",
    image: "https://pics.paypal.com/00/p/NWMyMzM0ZTYtZTA3ZS00MGUxLWFkMzItMGE5NDUzNDFlNjMw/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-super-world-2",
    name: "Super Abel123 World 2",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 2 in de Super Abel123 World-reeks.",
    description: "Het tweede deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "F33GLB3W3CP7N",
    image: "https://pics.paypal.com/00/p/Yzk0MjFmNTUtMzkyYi00ZjE5LWE5ODUtMGIxMzk5Y2ZiMjAw/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-super-world-1",
    name: "Super Abel123 World 1",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Platformgame — deel 1 in de Super Abel123 World-reeks.",
    description: "Het eerste deel in de Super Abel123 World platformgame-serie.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "7DWU56DLEMYLU",
    image: "https://pics.paypal.com/00/p/N2RkMGMzM2UtYTQ2OS00NGNjLTgyYWYtNzJiOWQ5ODc5NTQz/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-mario-android",
    name: "Mario 90s · 2030 · Builder · Matrix · Dimension (Android)",
    category: "game",
    platform: "Universeel",
    price: 9.99,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Bundel Android-games in de Mario-reeks.",
    description: "Een bundel van meerdere Mario Android-games in verschillende thema's.",
    specs: { "Platform": "Android", "Formaat": "Digitale download" },
    paypalId: "P3TZE99UGD9EY",
    image: "https://pics.paypal.com/00/p/NjU0NzNlMDQtZTk2My00NjM0LTkwOGEtZjVkOTFkMWYwNjIz/image_2.JPG",
    weroUrl: "https://buy.stripe.com/5kQdR28JOeRfeT1bBr6Zy03"
  },
  {
    id: "p-demolition-game",
    name: "Abel123 Demolition Game",
    category: "game",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Actiegame rondom sloop- en vernietigingsuitdagingen.",
    description: "Een actiegame waarin je gebouwen en objecten mag slopen.",
    specs: { "Genre": "Actie", "Formaat": "Digitale download" },
    paypalId: "HMTVUK97GVGNG",
    image: "https://pics.paypal.com/00/p/YTc0ZGVhMTYtODYyYi00MGM1LWE4YjctNWM4ODA1MjIxYjJh/image_2.JPG",
    weroUrl: "https://buy.stripe.com/14A9AM2lq6kJ26f34V6Zy08"
  },
  {
    id: "p-mars-climb",
    name: "Mars Climb Spacer",
    category: "game",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "🚀",
    tag: null,
    short: "Klimgame in een Mars-thema.",
    description: "Een casual klim/platformgame met een ruimtethema op Mars.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "RYXEHD683PCWY",
    image: "https://pics.paypal.com/00/p/NDgzNTlhN2UtNTU1Mi00NmY5LTgwMmUtZGQ5MTI0ZGM0ZGVm/image_2.JPG",
    weroUrl: "https://buy.stripe.com/14A9AM2lq6kJ26f34V6Zy08"
  },
  {
    id: "p-moon-climb",
    name: "Moon Climb Spacer",
    category: "game",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "🚀",
    tag: null,
    short: "Klimgame in een maanthema.",
    description: "Een casual klim/platformgame met een ruimtethema op de maan.",
    specs: { "Genre": "Platformer", "Formaat": "Digitale download" },
    paypalId: "ASP4MBWQKHYS4",
    image: "https://pics.paypal.com/00/p/MThhOGY1NTEtMzQ0OS00ZTJlLWJmYjYtZDBiZTUwMTQwNDIx/image_2.JPG",
    weroUrl: "https://buy.stripe.com/14A9AM2lq6kJ26f34V6Zy08"
  },

  // ---------------- WMWARIO REEKS ----------------
  {
    id: "p-mario-luigi-3d",
    name: "Mario & Luigi 3D Happy World (Multiplayer)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "3D multiplayer platformgame in de Mario-reeks.",
    description: "Een 3D platformgame met multiplayer-ondersteuning uit de Mario Happy World-serie.",
    specs: { "Genre": "3D Platformer", "Multiplayer": "Ja", "Formaat": "Digitale download" },
    paypalId: "U5GBLF47SEUC6",
    image: "https://pics.paypal.com/00/p/NzUzYjM2MGYtMjRmOC00ZDI2LWI5YzItZTQwYzk4NzQ4YjNh/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-mario-2026",
    name: "Mario Happy World 2026 (8-in-1 PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "8-in-1 pc-gamebundel in de Mario Happy World-reeks.",
    description: "Een bundel van acht games in één pc-pakket uit de Mario Happy World-serie.",
    specs: { "Platform": "PC", "Inhoud": "8-in-1 bundel", "Formaat": "Digitale download" },
    paypalId: "MNRG8ZTCQE9LJ",
    image: "https://pics.paypal.com/00/p/MTU0OWIwMGQtNTVjZC00MTI0LTk1ODAtYmM2YmJkMTY4NzIz/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-mario-fantasy",
    name: "Mario Happy World Fantasy (Webserver)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Webserver-versie van Mario Happy World in een fantasy-thema.",
    description: "Een via webserver speelbare versie van Mario Happy World met een fantasy-thema.",
    specs: { "Platform": "Webserver", "Formaat": "Digitale download" },
    paypalId: "USH33D3ECTQBN",
    image: "https://pics.paypal.com/00/p/ZjdjNWI5ZmYtYTE3ZC00OWYxLWI2ZjctMzZkY2FlZjhmNzAw/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-mario-12",
    name: "Mario Happy World 12 (PC)",
    category: "game",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 12 van de Mario Happy World pc-reeks.",
    description: "Het twaalfde deel in de Mario Happy World pc-gameserie.",
    specs: { "Platform": "PC", "Formaat": "Digitale download" },
    paypalId: "9DYATEXHR22U4",
    image: "https://pics.paypal.com/00/p/NjVkYjIzYWUtNDkyOC00MDcwLWI4ZGMtODVmYTFiNWM3MTdh/image_2.JPG",
    weroUrl: "https://buy.stripe.com/14A9AM2lq6kJ26f34V6Zy08"
  },
  {
    id: "p-mario-11",
    name: "Mario Happy World 11 (PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 11 van de Mario Happy World pc-reeks.",
    description: "Het elfde deel in de Mario Happy World pc-gameserie.",
    specs: { "Platform": "PC", "Formaat": "Digitale download" },
    paypalId: "WXQZ6GHP3S8KG",
    image: "https://pics.paypal.com/00/p/N2QzZmM4MzgtZTYxNC00NWMwLWIyMGEtY2VkZjBiYmQ3ODI0/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-mario-10",
    name: "Mario Happy World 10 (PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 10 van de Mario Happy World pc-reeks.",
    description: "Het tiende deel in de Mario Happy World pc-gameserie.",
    specs: { "Platform": "PC", "Formaat": "Digitale download" },
    paypalId: "NEDQ4N36E8HCG",
    image: "https://pics.paypal.com/00/p/MzRjNmI4ODItNmFmYy00MGNlLTk2OGItNzQwMWFlNDAzYzZj/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-mario-9",
    name: "Mario Happy World 9 (PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 9 van de Mario Happy World pc-reeks.",
    description: "Het negende deel in de Mario Happy World pc-gameserie.",
    specs: { "Platform": "PC", "Formaat": "Digitale download" },
    paypalId: "LXTBSKQCJW3AY",
    image: "https://pics.paypal.com/00/p/MmQ4MGYyODgtNjczNy00NTI1LWFhMzYtZDBhM2MzMjBjNWY3/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-mario-8",
    name: "Mario Happy World 8 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 8 van de Mario Happy World-reeks, voor Android en pc.",
    description: "Het achtste deel in de Mario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "U5CKDXUJ66V74",
    image: "https://pics.paypal.com/00/p/OTA4MzM5MmUtMThjZi00YWIwLTk3NGUtNzI3M2JhNTEzZWRh/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-mario-6",
    name: "Mario Happy World 6 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 2.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 6 van de Mario Happy World-reeks, voor Android en pc.",
    description: "Het zesde deel in de Mario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "UZJJKSP9FLMQ8",
    image: "https://pics.paypal.com/00/p/MzllNWFjOWEtMWQ0ZC00OGIwLTkwMTAtNGJlY2Q1ODdiYmM4/image_2.JPG",
    weroUrl: "https://buy.stripe.com/14A9AM2lq6kJ26f34V6Zy08"
  },
  {
    id: "p-mario-4",
    name: "Mario Happy World 4 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 4 van de Mario Happy World-reeks, voor Android en pc.",
    description: "Het vierde deel in de Mario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "LKDVU4S7693HA",
    image: "https://pics.paypal.com/00/p/ZmI4Nzk4NjctZGY2ZS00NDcwLWI1NGQtODU0YTgxNTc3NmM3/image_2.JPG",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },
  {
    id: "p-mario-3",
    name: "Mario Happy World 3 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 9.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 3 van de Mario Happy World-reeks, voor Android en pc.",
    description: "Het derde deel in de Mario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "E5NAUQHKLVA86",
    image: "https://pics.paypal.com/00/p/NTQzZTY1YzItODg3Zi00NjU0LWJlNDctNDI3OWNjNzM5YzQy/image_2.JPG",
    weroUrl: "https://buy.stripe.com/5kQdR28JOeRfeT1bBr6Zy03"
  },
  {
    id: "p-mario-2",
    name: "Mario Happy World 2 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 2 van de Mario Happy World-reeks, voor Android en pc.",
    description: "Het tweede deel in de Mario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "YHY5GEYZB6NB8",
    image: "https://pics.paypal.com/00/p/NDIxNzQ0NDEtMWMwMy00YWFmLTlmMWQtOWE4Y2I1NDM2OTg5/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-mario-1",
    name: "Mario Happy World 1 (Android/PC)",
    category: "game",
    platform: "Universeel",
    price: 4.99,
    stock: 999,
    glyph: "💿",
    tag: null,
    short: "Deel 1 van de Mario Happy World-reeks, voor Android en pc.",
    description: "Het eerste deel in de Mario Happy World-gameserie, beschikbaar voor Android en pc.",
    specs: { "Platform": "Android / PC", "Formaat": "Digitale download" },
    paypalId: "KPHFXFJ5SAFKJ",
    image: "https://pics.paypal.com/00/p/NTg3ZTliMTUtMWFlZC00ZTExLWI3MmYtYjEzMzRlNDM0MzA5/image_2.JPG",
    weroUrl: "https://buy.stripe.com/28E14ggcgeRfdOX9tj6Zy01"
  },
  {
    id: "p-mario-happy-app",
    name: "Mario Happy (Android App)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Android-app in de Mario Happy-reeks.",
    description: "Een Android-app uit de Mario Happy-serie.",
    specs: { "Platform": "Android", "Formaat": "Digitale download" },
    paypalId: "7L36E2XCNG9B2",
    image: "https://pics.paypal.com/00/p/YzU3YjVmNzQtYTBkYy00OTBlLTkzY2YtNjdhZmRmNTM2YzRi/image_2.JPG",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },

  // ---------------- OVERIGE ANDROID GAMES & APPS ----------------
  {
    id: "p-slotpipes",
    name: "Mario Slotpipes (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Puzzelgame met slots en pijpen, voor Android.",
    description: "Een Android-puzzelgame waarin je pijpen en slots met elkaar verbindt.",
    specs: { "Platform": "Android", "Genre": "Puzzel", "Formaat": "Digitale download" },
    paypalId: "AS8XU2UTZUFDA",
    image: "https://pics.paypal.com/00/p/ZWIwNjliYzktNDVhYS00ZWY0LWI0MGEtZjlhOTk1NjE0ZjFh/image_2.PNG",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },
  {
    id: "p-fluppy-burd",
    name: "Fluppy Burd Blocks (Android)",
    category: "game",
    platform: "Universeel",
    price: 1.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Casual blokkenpuzzel-vogelgame voor Android.",
    description: "Een luchtige casual game met blokken en een vogel als hoofdpersonage, voor Android.",
    specs: { "Platform": "Android", "Genre": "Puzzel", "Formaat": "Digitale download" },
    paypalId: "CSJAKU42XZLG6",
    image: "https://pics.paypal.com/00/p/NGJjYmQ0YjEtNWEzMy00YmMwLTkzMzYtYWY1NGYwOGNhZjll/image_2.JPG",
    weroUrl: "https://buy.stripe.com/eVq14g3pugZn7qz6h76Zy0a"
  },
  {
    id: "p-slotmoji",
    name: "SlotMoji (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Emoji-thema slotgame voor Android.",
    description: "Een casual slotgame met een emoji-thema, voor Android.",
    specs: { "Platform": "Android", "Genre": "Casual", "Formaat": "Digitale download" },
    paypalId: "YT7YX5KJUAC94",
    image: "https://pics.paypal.com/00/p/NWJjYzU0Y2UtN2ZkNy00NzMxLWIxMTgtYTc5ZjE1ZTdkMDc1/image_2.JPG",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },
  {
    id: "p-mario-crush",
    name: "Mario Crush Saga (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Match-stijl puzzelgame voor Android in de Mario-reeks.",
    description: "Een match-gebaseerde puzzelgame uit de Mario-serie, voor Android.",
    specs: { "Platform": "Android", "Genre": "Puzzel", "Formaat": "Digitale download" },
    paypalId: "FJCQPYBAD5UG4",
    image: "https://pics.paypal.com/00/p/ZjU5ODM1OGYtOWFkYy00ZGZlLTk3ZmItZjQ3Yjk3ZWUzYTFj/image_2.JPG",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },
  {
    id: "p-kross-zero",
    name: "Kross and Zero (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Boter-kaas-en-eieren-stijl game voor Android.",
    description: "Een Android-game geïnspireerd op het klassieke Kruisje-Rondje spel.",
    specs: { "Platform": "Android", "Genre": "Puzzel / Bordspel", "Formaat": "Digitale download" },
    paypalId: "7K2GYD5LUSSJ4",
    image: "https://pics.paypal.com/00/p/YjYyMzk3N2MtMjIxNS00MjhjLThiMmMtZjRlNzVkZTVjNGRj/image_2.JPG",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  },
  {
    id: "p-yf-arrows",
    name: "YF Arrows (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.00,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Pijl-gebaseerde puzzelgame voor Android.",
    description: "Een Android-puzzelgame gebaseerd op het richten en verbinden van pijlen.",
    specs: { "Platform": "Android", "Genre": "Puzzel", "Formaat": "Digitale download" },
    paypalId: "6GVUTFNE3KLDU",
    image: "https://pics.paypal.com/00/p/NDhlOWZiMTktM2JhYi00OTRiLWJhYmItZTIyMjU1MDYyMjg4/image_2.JPG",
    weroUrl: "https://buy.stripe.com/9B6eV62lqgZn3aj6h76Zy09"
  },
  {
    id: "p-flying-dutchman",
    name: "Flying Dutchman (Android)",
    category: "game",
    platform: "Universeel",
    price: 2.50,
    stock: 999,
    glyph: "📱",
    tag: null,
    short: "Avonturengame in nautisch thema voor Android.",
    description: "Een Android-avonturengame geïnspireerd op de legende van de Vliegende Hollander.",
    specs: { "Platform": "Android", "Genre": "Avontuur", "Formaat": "Digitale download" },
    paypalId: "YJUU798QTPPHY",
    image: "https://pics.paypal.com/00/p/OGI5NGVhZDMtY2E4Yy00Y2M1LTgzOTktY2U4ODk5MDQ5NWVi/image_2.JPG",
    weroUrl: "https://buy.stripe.com/4gM7sE2lq9wVdOXdJz6Zy07"
  }
];

/* Helper lookups */
function getProductById(id){
  return PRODUCTS.find(p => p.id === id);
}
function formatPrice(n){
  return "€ " + n.toFixed(2).replace(".", ",");
}
